version: '3'
services:
  db_aurora:
    image: postgres:latest
    environment:
      POSTGRES_DB: todos_db
      POSTGRES_USER: test_user
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  default:
    name: test-network
